export const FETCH_PRODUCTOS = "FETCH_PRODUCTOS";
export const FILTRAR_PRODUCTOS_POR_TALLA = "FILTRAR_PRODUCTOS_POR_TALLA";
export const ORDENAR_PRODUCTOS_POR_PRECIO = "ORDENAR_PRODUCTOS_POR_PRECIO";
export const AGREGAR_AL_CARRO = "AGREGAR_AL_CARRO"; 
export const SACAR_DEL_CARRO = "SACAR_DEL_CARRO";

